### ISSUE TITLE
BUG: Missing entries in coil_def.dat`

### ISSUE THREAD

**Issue by larsoner** [mne-tools/fiff-constants#14]
The `coil_def.dat` in MNE does not have entries for coil_type:
- 3015: MEG-MRI proto system planar gradiometer, or
- 3025: MEG-MRI proto system magnetometer

@jnenonen can these be removed, or do you have the appropriate coil defs for these coils?

**Comment by jnenonen** [comment]
Please remove these, they are not in use yet and concern only one specific prototype system.

**Comment by jnenonen** [comment]
Hi, 
Just looking at the defs:
---
    baby_grad           7001  "Baby-SQUID gradiometer"
    baby_mag_inner      7002  "BabyMEG inner layer magnetometer"
    baby_mag_outer      7003  "BabyMEG outer layer magnetometer"
    baby_mag_ref        7004  "BabyMEG reference layer magnetometer"
    artemis123_grad     7501  "Artemis123 gradiometer"
    artemis123_ref_mag  7502  "Artemis123 reference magnetometer"
    artemis123_ref_grad 7503  "Artemis123 reference gradiometer"
    kriss_grad          9001  "KRISS gradiometer"
    compumedics_adult_grad      10001  "Compumedics adult gradiometer"
    compumedics_pediatric_grad  10002  "Compumedics pediatric gradiometer"
---
1) Can we reserve range 8001 - 8999 for OPM sensors?
2) Is there particular need to go beyond 10000; i.e. are compumedics defs already in use somewhere? If not, I would suggest to move them e.g. to 10001->9101 and 10002->9102.

**Comment by agramfort** [comment]
ok for me to keep OPMs in 8000 range but I don't know who added the compumedics constants.

any idea @mshamalainen @larsoner or maybe @LorenzE ?

**Comment by LorenzE** [comment]
We added the compumedics coils after talking to Michael Wagner (Software dev at Compumedics) at BIOMAG 2018. If this is still of interest I can shoot him a message and get his opinion on the matter.
