### ISSUE TITLE
Q: Release 1.4?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/fiff-constants#20]
GitHub has a "releases" feature that we can use to make releases of the `fiff-constants`. @jnenonen I think #19 was the last thing we needed to change for the 1.4 version MEGIN , right? If so, I'll make a release on GitHub (which really means an archived version shows up in the `Releases` GitHub tab). Then future PRs that get merged will be set to be part of the 1.5 release, and so on.

**Comment by jnenonen** [comment]
You could still add new fnirs tags to 1.4, we have not yet closed it.

**Comment by larsoner** [comment]
Okay, let me know when you have finalized/released 1.4 and I'll make an official GitHub release to match.

**Comment by larsoner** [comment]
Done, closing
