### ISSUE TITLE
mne.Info - offer more complete options for subject handedness

### ISSUE THREAD

**Issue by dominikwelke** [mne-tools/fiff-constants#25]
dear all, 
first of all thanks for your amazing work!

I find in the [api documentation](https://mne.tools/dev/generated/mne.Info.html#mne.Info) that `mne.Info` objects currently only allow two options for a subjects handedness:

`hand : int`
`Handedness (1=right, 2=left).`

is there a specific reason for this? otherwise I would propose adding additional / more complete options:

`hand : int`
`Handedness (0=n/a, 1=right, 2=left, 3=ambidextrous).`

best, Dominik

**Comment by larsoner** [comment]
cc @jnenonen any thoughts on expanding the list of `handedness` to include `ambidextrous`, and possible other option(s) to `sex` in the subject info fields?

**Comment by jnenonen** [comment]
Hi Eric,

Please feel free to add suggestions for the next FIFF dictionary.

BR, Jukka

[cid:image002.png@01D5EAF0.136FC3C0]

**Comment by larsoner** [comment]
@dominikwelke can you open a PR for `handedness`?

@hoechenberger can you make one for `sex`?

**Comment by dominikwelke** [comment]
see #26
